version: 0.2
phases:
  pre_build:
    commands:
      - echo "Executed Pre_Build Phase"

  build:
    commands:
      - echo "Entered Build Phase"
      - mvn clean prepare-package war-exploded

  post_build:
    commands:
      - echo "Entered Post_Build Phase"
      - mv ./target/deploy ./

artifacts:
  files:
    - deploy/**/*